services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Etc/UTC
      - VERSION=docker
      #- PLEX_CLAIM= #optional
    volumes:
        - ./config/plex:/config
        - '${SERIES_PATH}:/tv'
        - '${MOVIES_PATH}:/movies'
    restart: unless-stopped
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Etc/UTC
      - PORT=5055
    ports:
      - 5055:5055
    volumes:
        - ./config/overseerr:/app/config
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Etc/UTC
    volumes:
        - ./config/radarr:/config
        - '${MOVIES_PATH}:/movies'
        - '${DOWNLOAD_PATH}:/downloads'
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Etc/UTC
    volumes:
        - ./config/sonarr:/config
        - '${SERIES_PATH}:/tv'
        - '${DOWNLOAD_PATH}:/downloads'
    ports:
      - 8989:8989
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Etc/UTC
      - AUTO_UPDATE=true
    volumes:
        - ./config/jackett:/config
        - '${DOWNLOAD_PATH}:/downloads'
    ports:
      - 9117:9117
    restart: unless-stopped
  flaresolverr:
      image: ghcr.io/flaresolverr/flaresolverr:latest
      container_name: flaresolverr
      environment:
        - LOG_LEVEL=info
        - LOG_HTML=false
        - CAPTCHA_SOLVER=none
        - TZ=Etc/UTC
      ports:
        - 8191:8191
      restart: unless-stopped
  tautulli:
      image: lscr.io/linuxserver/tautulli:latest
      container_name: tautulli
      environment:
        - PUID=${UID}
        - PGID=${GID}
        - TZ=Etc/UTC
      volumes:
        - ./config/tautulli:/config
      ports:
        - 8181:8181
      restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
        - ./config/qbittorrent:/config
        - ./qbitt-ui:/qbitt-ui
        - '${DOWNLOAD_PATH}:/downloads'
        - '${TEMP_DOWNLOAD_PATH}:/incomplete'
    ports:
      - 8080:8080
      - 9000:9000
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  #telebot:
  #  container_name: telebot
  #  network_mode: bridge
  #  environment:
  #    - PUID=${UID}
  #    - PGID=${GID}
  #  build:
  #    context: ./
  #    dockerfile: ./telebot/Dockerfile
  #  command: sh -c "sleep 2s ; python3 ./source/main.py"
  #  restart: unless-stopped